---
name: Changelog & versions
"on":
  push:
    branches:
      - main
    paths:
      - changelog.md
      - .bumpversion.cfg
      - .github/workflows/changelog.yaml
      - .github/workflows/release.yaml

concurrency:
  # Group workflow jobs so new commits cancels in-progress execution triggered by previous commits.
  # Source: https://twitter.com/sebastienlorber/status/1495776331287646209
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  changelog:
    uses: kdeldycke/workflows/.github/workflows/changelog.yaml@v1.4.2
