---
name: Labels
"on":
  push:
    branches:
      - main

concurrency:
  # Group workflow jobs so new commits cancels in-progress execution triggered by previous commits.
  # Source: https://twitter.com/sebastienlorber/status/1495776331287646209
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  labels:
    uses: kdeldycke/workflows/.github/workflows/labels.yaml@v1.4.2
